### ISSUE TITLE
`prettier/@typescript-eslint` in ESLint config now throws error

### ISSUE THREAD

**Issue by MikeRossXYZ** [nestjs/mapped-types#962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running `npm run lint` locally, the command does not complete due to an error:

```
$ npm run lint

> @nestjs/mapped-types@1.2.0 lint
> eslint 'lib/**/*.ts' --fix


Oops! Something went wrong! :(

ESLint: 8.32.0

Error: Cannot read config file: /Users/rossm/projects/mapped-types/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /Users/rossm/projects/mapped-types/.eslintrc.js
    at Object.<anonymous> (/Users/rossm/projects/mapped-types/node_modules/eslint-config-prettier/@typescript-eslint.js:1:7)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at module.exports [as default] (/Users/rossm/projects/mapped-types/node_modules/import-fresh/index.js:31:59)
    at loadJSConfigFile (/Users/rossm/projects/mapped-types/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2562:47)
    at loadConfigFile (/Users/rossm/projects/mapped-types/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2646:20)
    at ConfigArrayFactory._loadConfigData (/Users/rossm/projects/mapped-types/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2963:42)
```

### Minimum reproduction code

Not applicable -- reproducible from command line alone

### Steps to reproduce

1. `npm run lint`

### Expected behavior

```
$ npm run lint
```

Output:

```
> @nestjs/mapped-types@1.2.0 lint
> eslint 'lib/**/*.ts' --fix
```

### Package version

1.2.0

### Node.js version

18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/mapped-types/pull/961
